---
abstract: 'Mixin methods for simple event/message dispatch framework'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  Capture::Tiny: 0
  Test::CheckDeps: 0.006
  Test::Fatal: 0.010
  Test::More: 0.98
  Test::Refcount: 0.07
  blib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300036, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mixin-Event-Dispatch
requires:
  List::UtilsBy: 0
  Try::Tiny: 0
  parent: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Mixin-Event-Dispatch
  homepage: http://search.cpan.org/dist/Mixin-Event-Dispatch/
version: 1.002
