---
abstract: 'Mixin methods for simple event/message dispatch framework'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  Test::More: 0.84
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mixin-Event-Dispatch
requires:
  List::UtilsBy: 0
  Try::Tiny: 0
  parent: 0
version: 0.004
